### ISSUE TITLE
updated jar that includes item steerable fix for 1.19.3 hasnt been released yet

### ISSUE THREAD

**Issue by queenbiscuit311** [Camotoy/GeyserHacks#10]
Is there a reason for this? The update is on the repository and after figuring out how to compile the plugin myself and adding the v1_19_R2 module to the 1.2-SNAPSHOT-2 jar file everythings working perfectly as intended on 1.19.3 as far as i can tell. i imagine a lot of people arent going to go through the trouble of building it themselves and then figuring out how to put it together when it seems like it could just easily be released as a jar file.
![image](https://user-images.githubusercontent.com/88851292/210128486-5f30c6c6-964b-4c48-aeed-376a93668cb4.png)

**Comment by Camotoy** [comment]
I didn't realize the build didn't get compiled. But I can't see the error on mobile, so it seems.

**Comment by queenbiscuit311** [comment]
ah that makes sense
