### ISSUE TITLE
Disable sprint button while the player is Crawling

### ISSUE THREAD

**Issue by MinecraftNight4** [Camotoy/GeyserHacks#12]
I have noticed that some players are using the SPRINTING button, while they are using the crawling system that Geyser implemented.

This is causing me some false reports in the anticheat and after trying various things, I found that a potential way to fix this is to set the player's hunger to 6 while in that mode.

Would it be possible to add an option that changes the player's hunger so that he can't use the sprint button?

**Comment by Camotoy** [comment]
I believe we have an open issue for this on Geyser - I don't think this is something we need to use GeyserHacks for, as I think this bug didn't exist at one point?

Of course I wish for the bug to be fixed, but I'll probably focus on it once 1.19.70 is released and sneaking under 1.5 blocks is properly supported in Bedrock.
