### ISSUE TITLE
Request to employ fix for headless Armor Stand

### ISSUE THREAD

**Issue by PikaMug** [Camotoy/GeyserHacks#7]
From the [wiki](https://wiki.geysermc.org/geyser/current-limitations/):
```
The following things cannot be fixed without changes to Bedrock or the Java protocol in general...

    - Blocks (excluding jack-o-lantern) on entity heads (E.G. armor stands, players)
```

If the head of an Armor Stand uses an unsupported block, have GeyserHacks display it as Carved Pumpkin instead of naught. Particularly useful for Spigot plugins such as [GPS](https://www.spigotmc.org/resources/53672/).

**Comment by Camotoy** [comment]
Please leave an issue for this on the main Geyser repository. This is something we can accomplish without server-side hacks.
